package com.epam.musicapp.user.management.mapper;

import com.epam.musicapp.user.management.entity.User;
import com.epam.musicapp.user.management.request.UserRequest;
import jakarta.annotation.PostConstruct;
import org.modelmapper.ModelMapper;
import org.modelmapper.PropertyMap;
import org.springframework.stereotype.Component;

@Component
public class UserMapper {

    private final ModelMapper modelMapper;

    public UserMapper(ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

    @PostConstruct
    public void configureModelMapper() {
        modelMapper.addMappings(new PropertyMap<UserRequest, User>() {
            @Override
            protected void configure() {
                skip(destination.getUserId());  // Assuming User Id is autogenerated and should be skipped
            }
        });
    }

    public User mapUserRequestToEntity(UserRequest userRequest) {
        return modelMapper.map(userRequest, User.class);
    }


}
